config/routes.rb
Ujumbox::Application.routes.draw do
  resources :acts
  resources :ujumbes

  root :to => "ujumbes#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
  	member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    resources :acts
  end

  get "about" => "about#show"
  get "politics" => "home#politics"
  get "citizen" => "home#citizen"
  get "rosemefalessi" => "users#show", defaults: { id: "10" }

end

app/models/ujumbe.rb
class Ujumbe < ActiveRecord::Base
	belongs_to :user
	has_many :acts, :dependent => :destroy
	accepts_nested_attributes_for :acts
	 
	acts_as_followable

	has_attached_file :image, 
                    :styles => { :medium => "400x400#", :thumb => "100x100#", :mini => "50x50#", :large => "600x600#" }, 
                    :default_url => "logo_ujumbox.png"

	
	validates :title, presence: true

	def politic
		user.is_politic?
	end

	def civil
		!politic
	end

end

app/controllers/ujumbes_controller.rb
class UjumbesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_ujumbe, only: [:show, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]

  # GET /ujumbes
  # GET /ujumbes.json
  def index
    @ujumbes = Ujumbe.all.order('id DESC')
    @ujumbe = current_user.ujumbes.build if current_user
    @user = current_user
  end

  # GET /ujumbes/1
  # GET /ujumbes/1.json
  def show
    @user = current_user
  end

  def follow
    @ujumbe = Ujumbe.find(params[:id])
    current_user.follow(@ujumbe)
    redirect_to :back
  end

  def unfollow
    @ujumbe = Ujumbe.find(params[:id])
    current_user.stop_following(@ujumbe)
    redirect_to :back
  end

  # GET /ujumbes/new
  def new
    @ujumbe = current_user.ujumbes.build
    @user = current_user
  end

  # GET /ujumbes/1/edit
  def edit
    @user = current_user
  end

  # POST /ujumbes
  # POST /ujumbes.json
  def create
    @ujumbe = current_user.ujumbes.build(ujumbe_params)
    @user = current_user

    respond_to do |format|
      if @ujumbe.save
        format.html { redirect_to edit_ujumbe_path(@ujumbe), notice: 'Ujumbe was successfully created. You can now complete it' }
        format.json { render action: 'show', status: :created, location: @ujumbe }
      else
        format.html { render action: 'new' }
        format.json { render json: @ujumbe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ujumbes/1
  # PATCH/PUT /ujumbes/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @ujumbe.update(ujumbe_params)
        format.html { redirect_to @ujumbe, notice: 'Ujumbe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ujumbe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ujumbes/1
  # DELETE /ujumbes/1.json
  def destroy
    @ujumbe.destroy
    respond_to do |format|
      format.html { redirect_to ujumbes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ujumbe
      @ujumbe = Ujumbe.find(params[:id])
    end

    def correct_user
      @ujumbe = current_user.ujumbes.find_by(id: params[:id])
      redirect_to ujumbes_path, notice: t("Vous ne pouvez pas modifier cela") if @ujumbe.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ujumbe_params
      params.require(:ujumbe).permit(:title, :theme, :date, :description, :link, :type, :private,
                                     :what, :why, :how, :budget, :funding,
                                     :theme_ressources, :theme_education, :theme_housing, :theme_environnement, :theme_culture, :theme_economy, :theme_social, :theme_security, :theme_scientific, :theme_foreign,
                                     :image)
    end
end

app/helpers/ujumbes_helper.rb
module UjumbesHelper
end

app/views/ujumbes/_form.html.erb
  <%= simple_form_for(@ujumbe) do |f| %>
  <%= f.error_notification %>


  <div class="form-group">
    <% if current_user.is_politic %>
      <%= f.label :title, "Votre proposition" %>
    <% else %>
      <%= f.label :title, "Votre suggestion" %>
    <% end %>
      <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if current_user.is_politic %>
      <%= f.label :what, "Décrivez votre proposition" %>
    <% else %>
      <%= f.label :what, "Décrivez votre suggestion" %>
    <% end %>
      <%= f.text_area :what, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if current_user.is_politic %>
    <%= f.label :action_areas, "Indiquez le/les domaines impactés par votre proposition" %>
    <% else %>
    <%= f.label :action_areas, "Indiquez le/les domaines impactés par votre suggestion" %>
    <% end %>
    <ul class="list-group">
      <li class="list-group-item"><%= f.check_box :theme_education %> éducation, jeunesse</li>
      <li class="list-group-item"><%= f.check_box :theme_economy %> économie, emploi</li>
      <li class="list-group-item"><%= f.check_box :theme_housing %> logement</li>
      <li class="list-group-item"><%= f.check_box :theme_social %> sécurité sociale, fiscalité</li>
      <li class="list-group-item"><%= f.check_box :theme_culture %> culture, sport</li>
      <li class="list-group-item"><%= f.check_box :theme_environnement %> environnement, aménagement du territoire</li>
      <li class="list-group-item"><%= f.check_box :theme_ressources %> eau, énergie, agriculture</li>
      <li class="list-group-item"><%= f.check_box :theme_security %> police, armée, justice</li>
      <li class="list-group-item"><%= f.check_box :theme_scientific %> recherche scientifique</li>
      <li class="list-group-item"><%= f.check_box :theme_foreign %> affaires étrangères</li>
    </ul>

  <div class="form-group">
      <%= f.label :why, "A quel problème souhaitez-vous ainsi remédier ?" %>
      <%= f.text_area :why, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if current_user.is_politic %>
      <%= f.label :how, "Comment allez-vous la mettre en oeuvre ?" %>
      <% else %>
      <%= f.label :how, "Avez-vous une suggestion de mise en oeuvre ?" %>
      <% end %>
      <%= f.text_area :how, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if current_user.is_politic %>
      <%= f.label :budget, "Quel est le budget nécessaire pour la mettre en oeuvre ?" %>
      <% else %>
      <%= f.label :budget, "Avez-vous une idée du budget nécessaire pour la mettre en oeuvre ?" %>
      <% end %>

      <%= f.text_area :budget, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if current_user.is_politic %>
      <%= f.label :funding, "D'où proviendront les fonds pour la mettre en oeuvre ?" %>
      <% else %>
      <%= f.label :funding, "Avez-vous une idée d'où pourraient provenir ces fonds ?" %>
      <% end %>
      <%= f.text_area :funding, class: 'form-control' %>
  </div>

  <div class="form-actions">
    <% if current_user.is_politic %>
    <%= f.submit "Publiez votre proposition", :class => "btn btn-primary" %>
    <% else %>
    <%= f.submit "Publiez votre suggestion", :class => "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/ujumbes/_inside.html.erb
      <div class="page-header">
        <div class="row">
          <div class="col-md-10">
            <h1>
              <% if @ujumbe.politic %>
            <i class="fa fa-microphone blujumbox fa-lg fa-border"></i>
            <% else %>
            <i class="fa fa-bullhorn blujumbox fa-lg fa-border"></i>
            <% end %>
              <%= @ujumbe.title %>
            <span class="center-text">
              <% if current_user == @ujumbe.user %>
                <% if @ujumbe.politic %>
                  <%= link_to 'Editez votre proposition', edit_ujumbe_path(@ujumbe), :class => 'btn btn-default' %>
                <% else %>
                  <%= link_to 'Editez votre suggestion', edit_ujumbe_path(@ujumbe), :class => 'btn btn-default' %>
                <% end %>

              <% else %>

                <% if current_user.following?(@ujumbe) %>
                  <%= link_to unfollow_ujumbe_path(@ujumbe) do %>
                    <%= content_tag(:i, " Ne plus suivre" ,:class=> 'fa fa-thumbs-down btn btn-default btn-lg') -%>
                  <% end %>
                <% else %>
                  <%= link_to follow_ujumbe_path(@ujumbe) do %>
                    <%= content_tag(:i, " Suivre" ,:class=> 'fa fa-thumbs-up btn btn-success btn-lg') -%>
                  <% end %>
                <% end %>

              <% end %>
            </span></h1>
          </div>
          <div class="col-md-2">
            <%= link_to image_tag(@ujumbe.user.image.url(:thumb), :class => "img-circle profilepic"), user_path(@ujumbe.user) %>
          </div>
        </div>
      </div>
      <div class="text-right lead">
            <% if @ujumbe.theme_education %><span class="label label-success">éducation, jeunesse</span><% end %>
            <% if @ujumbe.theme_economy %><span class="label label-success">économie, emploi</span><% end %>
            <% if @ujumbe.theme_housing %><span class="label label-success">logement</span><% end %>
            <% if @ujumbe.theme_social %><span class="label label-success"> sécurité sociale, fiscalité</span><% end %>
            <% if @ujumbe.theme_culture %><span class="label label-success"> culture, sport</span><% end %>
            <% if @ujumbe.theme_environnement %><span class="label label-success"> environnement</span><% end %>
            <% if @ujumbe.theme_ressources %><span class="label label-success"> eau, énergie, agriculture</span><% end %>
            <% if @ujumbe.theme_security %><span class="label label-success"> police, armée, justice</span><% end %>
            <% if @ujumbe.theme_scientific %><span class="label label-success"> recherche scientifique</span><% end %>
            <% if @ujumbe.theme_foreign %><span class="label label-success"> affaires étrangères</span><% end %>
          </div>

      <div class="col-md-10 col-md-offset-1">

      <% if @ujumbe.what.present? %>
        <p class="lead">
          <% if @ujumbe.politic %>
          Ma proposition dans le détail :
          <% else %>
          Ma suggestion dans le détail :
          <% end %>
        </p>
      <div class="thumbnail">
          <div class="caption">
      <%= simple_format(@ujumbe.what) %>
      </div>
      </div>
      <% end %>

      <% if @ujumbe.why.present? %>
      <p class="lead">
        <% if @ujumbe.politic %>
        Pourquoi cette proposition :
        <% else %>
        Pourquoi cette suggestion :
        <% end %>
      </p>
      <div class="thumbnail">
          <div class="caption">
      <%= simple_format(@ujumbe.why) %>
      </div>
      </div>
      <% end %>

      <% if @ujumbe.how.present? %>
      <p class="lead">
        <% if @ujumbe.politic %>
        La manière dont je compte mettre en oeuvre cette proposition :
        <% else %>
        La manière dont cette suggestion pourrait être mise en oeuvre :
        <% end %>
      </p>
      <div class="thumbnail">
          <div class="caption">
      <%= simple_format(@ujumbe.how) %>
      </div>
      </div>
      <% end %>


      <% if @ujumbe.budget.present? %>
      <p class="lead">
        <% if @ujumbe.politic %>
        Le budget nécessaire à la réalisation de cette proposition :
        <% else %>
        Le budget qui me paraît nécessaire à la réalisation de cette proposition :
        <% end %>
      </p>

      <div class="thumbnail">
          <div class="caption">
            <p><b>Budget</b></p>
      <p><%= @ujumbe.budget %></p>
      <p><b>Source de financement</b></p>
      <%= simple_format(@ujumbe.funding) %>
      </div>
      </div>
      <% end %>
      </div>

app/views/ujumbes/_shortform.html.erb
    <div class="thumbnail alert-info">
      <!-- <img data-src="holder.js/300x200" alt="..."> -->
      <div class="caption alert-info">

        <p class="lead">
          <% if current_user.is_politic %>
            <%= link_to 'Une nouvelle solution ?', new_ujumbe_path %>
          <% else %>
            <%= link_to 'Une préoccupation ?', new_ujumbe_path %>
          <% end %>
        </p>

        <%= simple_form_for(@ujumbe) do |f| %>
        <%= f.error_notification %>
          <div class="form-group">
            <% if current_user.is_politic %>
              <%= f.text_field :title, :placeholder => "Faites une nouvelle proposition", class: 'form-control input-lg' %>
            <% else %>
              <%= f.text_field :title, :placeholder => "Faites une nouvelle suggestion", class: 'form-control input-lg' %>
            <% end %>
          </div>


          <div class="form-actions">
            <% if current_user.is_politic %>
            <%= f.submit "Publiez votre proposition", :class => "btn btn-primary btn-block" %>
            <% else %>
            <%= f.submit "Publiez votre suggestion", :class => "btn btn-primary btn-block" %>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  

app/views/ujumbes/_stream.html.erb
<h1 class="page-header">Propositions politiques & suggestions citoyennes  <%= link_to 'Devenir utilisateur politique', "mailto:contact@ujumbox.com", :class => "btn btn-primary pull-right" unless current_user.is_politic %></h1>

<!-- pour plus tard 
<h3 class="text-center">Propositions dans vos thèmes | Propositions de vos candidats</h3>
-->

<% unless @ujumbes.any? %>
  <p class"text-center lead">Aucun candidat ou mandataire n'a encore pulbié de proposition</p>
<% end %>

<div class="col-sm-6 col-md-4">
<%= render 'shortform' %>
</div>




<% @ujumbes.each do |ujumbe| %>
  
  <div class="col-sm-6 col-md-4">
    <div class="panel">
      <!-- <img data-src="holder.js/300x200" alt="..."> -->
      <div class="panel-body card">
        
        
<!-- theme ! -->
      <p class="text-right"><% if ujumbe.theme_education %><span class="label label-success">éducation, jeunesse</span><% end %>
      <% if ujumbe.theme_economy %><span class="label label-success">économie, emploi</span><% end %>
      <% if ujumbe.theme_housing %><span class="label label-success">logement</span><% end %>
      <% if ujumbe.theme_social %><span class="label label-success"> sécurité sociale, fiscalité</span><% end %>
      <% if ujumbe.theme_culture %><span class="label label-success"> culture, sport</span><% end %>
      <% if ujumbe.theme_environnement %><span class="label label-success"> environnement</span><% end %>
      <% if ujumbe.theme_ressources %><span class="label label-success"> eau, énergie, agriculture</span><% end %>
      <% if ujumbe.theme_security %><span class="label label-success"> police, armée, justice</span><% end %>
      <% if ujumbe.theme_scientific %><span class="label label-success"> recherche scientifique</span><% end %>
      <% if ujumbe.theme_foreign %><span class="label label-success"> affaires étrangères</span><% end %>

      <% if ujumbe.politic %>
      <i class="fa fa-microphone blujumbox fa-lg"></i>
      <% else %>
      <i class="fa fa-bullhorn blujumbox fa-lg"></i>
      <% end %>
    </p>
    <br>

<!-- title ! -->
      <div class="title">
          <%= link_to truncate(ujumbe.title, :length => 48), ujumbe_path(ujumbe) %>
      </div>
  </div>


  <div class="panel-footer">
    <div class="row">
      <div class="col-md-2">
     <%= link_to image_tag(ujumbe.user.image.url(:mini), :class => "img-circle"), user_path(ujumbe.user) %>
   </div>
   <div class="col-md-5 col-md-offset-5"> 
      
    <% if current_user.following?(ujumbe) %>
          <%= link_to unfollow_ujumbe_path(ujumbe) do %>
            <%= content_tag(:i, " " ,:class=> 'fa fa-thumbs-down btn btn-default pull-right') -%>
          <% end %>
    <% else %>
      <%= link_to follow_ujumbe_path(ujumbe) do %>
            <%= content_tag(:i, " " ,:class=> 'fa fa-thumbs-up btn btn-success pull-right') -%>
          <% end %>
          
    <% end %>
    <%= link_to ujumbe_path(ujumbe) do %>
            <%= content_tag(:i, " " ,:class=> 'fa fa-eye btn btn-default pull-right') -%>
          <% end %>

  </div>

</div>
         
    </div>
        

  </div>





  </div>

<% end %>

app/views/ujumbes/_visitor.html.erb
<div class="visitorcontent">

  <div class="panel panel-default col-md-4 col-md-offset-3">
    <%= link_to image_tag(@ujumbe.user.image.url(:thumb), :class => "img-circle visitorpics"), user_path(@ujumbe.user) %>

     <div class="text-right visitortheme">
      <% if @ujumbe.theme_education %><span class="label label-success">éducation, jeunesse</span><% end %>
      <% if @ujumbe.theme_economy %><span class="label label-success">économie, emploi</span><% end %>
      <% if @ujumbe.theme_housing %><span class="label label-success">logement</span><% end %>
      <% if @ujumbe.theme_social %><span class="label label-success"> sécurité sociale, fiscalité</span><% end %>
      <% if @ujumbe.theme_culture %><span class="label label-success"> culture, sport</span><% end %>
      <% if @ujumbe.theme_environnement %><span class="label label-success"> environnement</span><% end %>
      <% if @ujumbe.theme_ressources %><span class="label label-success"> eau, énergie, agriculture</span><% end %>
      <% if @ujumbe.theme_security %><span class="label label-success"> police, armée, justice</span><% end %>
      <% if @ujumbe.theme_scientific %><span class="label label-success"> recherche scientifique</span><% end %>
      <% if @ujumbe.theme_foreign %><span class="label label-success"> affaires étrangères</span><% end %>
 


   </div>
 
    
  <h1>
    <% if @ujumbe.politic %>
      <i class="fa fa-microphone blujumbox fa-lg fa-border pull-left"></i>
      <% else %>
      <i class="fa fa-bullhorn blujumbox fa-lg fa-border pull-left"></i>
      <% end %>
      <%= @ujumbe.title %>
    </h1>
    <br>
  
 

  <p class="text-center"><%= link_to "Voir le détail", user_registration_path, :class => "btn btn-info btn-lg" %></p>
  <div class="text-center"><%= twitter_button :title => @ujumbe.title+" "+"#ujumbox #digitaldemocracy" %> </div>
  <!-- <%= social_share_button_tag(@ujumbe.title, url: ujumbe_url(@ujumbe)) %> -->


</div>

    



<div class="col-md-3 text-center visitorCTA">
      

      <p class="lead"><%= @ujumbe.user.name %> utilise 
        <span class="biggy ujumbox blujumbox">ujumbox</span>, 
        <br>une boîte à messages politique permettant de pratiquer la démocratie au quotidien</p>
        

      <p class="text-center"><%= link_to "S'inscrire sur ujumbox", new_user_registration_path, :class => "btn btn-primary btn-lg" %></p>

      <p><u><%= link_to "En savoir plus sur ujumbox", root_path %></u></p>
        
    </div>

</div>

app/views/ujumbes/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="page-header">

  <h1>
  	<% if current_user.is_politic %>
  	Complétez votre proposition
  	<% else %>
  	Complétez votre suggestion
  	<% end %>
  </h1>
</div>
<%= render 'form' %>

</div>

app/views/ujumbes/index.html.erb
<%= render "home/index" unless user_signed_in? %>
<%= render "stream" if user_signed_in? %>

app/views/ujumbes/new.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="page-header">

  <h1>
  	<% if current_user.is_politic %>
  	Nouvelle proposition
  	<% else %>
  	Nouvelle suggestion
  	<% end %>	
  </h1>
</div>

<%= render 'form' %>

</div>

app/views/ujumbes/show.html.erb
<% if signed_in? %>


 <%= render "inside" %>


<% else %>

    <%= render "visitor" %>

<% end %>