config/routes.rb
Ujumbox::Application.routes.draw do
  resources :acts
  resources :ujumbes

  root :to => "ujumbes#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
  	member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    resources :acts
  end

  get "about" => "about#show"
  get "politics" => "home#politics"
  get "citizen" => "home#citizen"
  get "rosemefalessi" => "users#show", defaults: { id: "10" }

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_follower
  acts_as_followable
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ujumbes
  has_many :acts, through: :ujumbes

  has_attached_file :image, 
                    :styles => { :medium => "400x400#", :thumb => "100x100#", :mini => "50x50#", :large => "600x600#" }, 
                    :default_url => "userpic_missing_:style.png"
                    
  
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
  validates_attachment_size :image, :less_than => 5.megabytes

  has_attached_file :cover, 
                    :styles => { :medium => "300x300#", :thumb => "100x100#", :cover => "1814x489#" }, 
                    :default_url => "usercover_missing_:style.png" 
                    
  
  validates_attachment :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] } 
  validates_attachment_size :cover, :less_than => 5.megabytes


  ACTION_AREAS = ["police", "fiscalite", "securite_sociale", "affaires_etrangeres", "armee", "justice", "recherche_scientifique", "amenagement_territoire", "environnement", "logement", "agriculture", "eau_energie", "economie_emploi", "culture", "sport", "education", "creches", "jeunesse"]

  def self.action_areas
    ACTION_AREAS.map do |action_area|
      [I18n.t("action_areas.#{action_area}"), action_area]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @ujumbes = @user.ujumbes.order('id DESC')
    @ujumbe = current_user.ujumbes.build if current_user
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to :back
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    redirect_to :back
  end

  def edit
    @user = current_user
    @action_areas = User.action_areas
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Votre profil a bien ete mis a jour"
    else
      render action: "edit", notice: "Oups, veuillez reessayer"
    end
  end

  def user_params
    params.require(:user).permit(:email, :name, :title, :career, :action_area, :achievements, :profession, :party, :party_short, :birth_date, :birth_place, :residency, :image, :cover, 
                                 :theme_ressources, :theme_education, :theme_housing, :theme_environnement, :theme_culture, :theme_economy, :theme_social, :theme_security, :theme_scientific, :theme_foreign,
                                 :facebook_url, :linkedin_url, :twitter_url, :website_url,
                                 :is_politic)
  end

  def markdown(content)
    markdown =Redcarpet::Markdown.new(Redcarpet::Render::XHTML,:hard_wrap=>true,:filter_html=>true,:autolink=>true,:no_intra_emphasis=>true)
    markdown.render(content).html_safe
  end

end

app/views/users/_followedujumbe.html.erb
<% if @user.following_ujumbes.any? %>
	
	<% @user.following_ujumbes.each do |ujumbe| %>
		
<div class="col-sm-6 col-md-6">
			
<div class="panel">
<!-- <img data-src="holder.js/300x200" alt="..."> -->
<div class="panel-body card">
	
      <p class="text-right">
	<% if ujumbe.theme_education %><span class="label label-success">éducation, jeunesse</span><% end %>
      <% if ujumbe.theme_economy %><span class="label label-success">économie, emploi</span><% end %>
      <% if ujumbe.theme_housing %><span class="label label-success">logement</span><% end %>
      <% if ujumbe.theme_social %><span class="label label-success"> sécurité sociale, fiscalité</span><% end %>
      <% if ujumbe.theme_culture %><span class="label label-success"> culture, sport</span><% end %>
      <% if ujumbe.theme_environnement %><span class="label label-success"> environnement</span><% end %>
      <% if ujumbe.theme_ressources %><span class="label label-success"> eau, énergie, agriculture</span><% end %>
      <% if ujumbe.theme_security %><span class="label label-success"> police, armée, justice</span><% end %>
      <% if ujumbe.theme_scientific %><span class="label label-success"> recherche scientifique</span><% end %>
      <% if ujumbe.theme_foreign %><span class="label label-success"> affaires étrangères</span><% end %>

      <% if ujumbe.politic %>
      <i class="fa fa-microphone blujumbox fa-lg"></i>
      <% else %>
      <i class="fa fa-bullhorn blujumbox fa-lg"></i>
      <% end %>
	</p>

      <div class="title"><%= link_to truncate(ujumbe.title, :length => 100), ujumbe_path(ujumbe) %></div>

</div>	
<div class="panel-footer">
      <div class="row">
            <div class="col-md-2">
                  <%= link_to image_tag(ujumbe.user.image.url(:mini), :class => "img-circle"), user_path(ujumbe.user) %>
            </div>

            <div class="col-md-5 col-md-offset-5">
            <% if current_user.following?(ujumbe) %>
                  <%= link_to unfollow_ujumbe_path(ujumbe) do %>
                        <%= content_tag(:i, " " ,:class=> 'fa fa-thumbs-down btn btn-default pull-right') -%>
                  <% end %>
            <% else %>
                  <%= link_to follow_ujumbe_path(ujumbe) do %>
                        <%= content_tag(:i, " " ,:class=> 'fa fa-thumbs-up btn btn-success pull-right') -%>
                  <% end %>   
            <% end %>
      
            <%= link_to ujumbe_path(ujumbe) do %>
                  <%= content_tag(:i, " " ,:class=> 'fa fa-eye btn btn-default pull-right') -%>
            <% end %>
            </div>
      </div>
</div>
							
</div> <!-- end panel -->
</div> <!-- end col -->
					
	<% end %>

<% else %>
	<p class="lead text-center"><%= @user.name %> ne suit pas encore de proposition ni de suggestion</p>
<% end %>

app/views/users/_followedusers.html.erb
<% if @user.following_users.any? %>
			
					<% @user.following_users.each do |user| %>
					
						<div class="col-sm-3 col-md-6">
							<div class="thumbnail">
								<%= link_to image_tag(user.image.url(:medium), :class => "img-thumbnail profilepic"), user_path(user) %>
								<div class="text-center"><b><%= link_to user.name, user_path(user) %></b></div>

								<div class="text-center">
			        	<% if current_user.following?(user) %>
          			<%= link_to 'Ne plus suivre', unfollow_user_path(user), :class => 'btn btn-default btn-block' %>
      				<% else %>
      					<%= link_to 'Suivre', follow_user_path(user), :class => 'btn btn-success btn-block' %>
      <% end %></div>
							</div>
						</div>
			
					<% end %>
				
				<% else %>
					<p class="lead text-center"><%= @user.name %> ne suit pas encore de candidat ou mandataire</p>
				<% end %>

app/views/users/_ifcitizen.html.erb
<!-- View if the profile is civil -->
<p class="lead text-center">
	<i class="fa fa-heart fa-lg blujumbox fa-border"></i>
	<%= render 'themesusers' %>
		</p>
<div class="row">

<!-- LEFT -->
	<div class="col-md-4">
					
				
				<p class=" lead text-center"><b>Candidats ou mandataires suivis</b></p>
			
				<%= render 'followedusers' %>

	</div>

<!-- RIGHT -->
		<div class="col-md-8">
			<div class="row">
				<p class="lead text-center"><b>Mes suggestions</b></p>
			
				<% if @user == current_user %>
					<div class="col-sm-6 col-md-6">
						<%= render 'ujumbes/shortform' %>
					</div>
				<% end %>

				<% if @ujumbes.any? %>
				<%= render 'ujumbe' %>
				<% else %>
					<% unless @user == current_user %>
						<p class="lead text-center"><%= @user.name %> n'a pas encore publié de suggestion</p>
					<% end %>
				<% end %>

			</div>
	

	<!-- FOLLOWED UJUMBES -->
			<div class="row">
	
				<p class="lead text-center"><b>Propositions et suggestions suivies</b></p>
		
				<%= render 'followedujumbe' %>
			</div>

		</div>

</div>

app/views/users/_ifpolitic.html.erb
<p class="lead text-center">
	<i class="fa fa-suitcase fa-lg blujumbox fa-border"></i>
	<%= render 'themesusers' %>
		</p>

<div class="row">
		
<!-- LEFT -->
		<div class="col-md-4">
			<p class=" lead text-center"><b>Mon engagement</b></p>

			<div class="thumbnail">
				<div class="caption">
					
					<br>
					<br>
		
					<p class="lead">Mon activité professionnelle</p>
					<p><%= @user.profession %></p>
					<br>
		
					<p class="lead">Mon parcours politique</p>
					<p><%= simple_format(@user.career) %></p>
					<br>

					<p class="lead">Mes réalisations passées</p>
					<p><%= simple_format(@user.achievements) %></p>
					<br>
		
				</div>
			</div>

			<!-- FOLLOWED USERS -->
<div class="row">
				<p class="lead text-center"><b>Candidats et mandataires suivis</b></p>
				
				<%= render 'followedusers' %>
			</div>
		</div>


<!-- RIGHT -->
		<div class="col-md-8">
			<div class="row">
			<p class="lead text-center"><b>Mes propositions</b></p>
			
			<% if @user == current_user %>
			<div class="col-sm-6 col-md-6">
				<%= render 'ujumbes/shortform' %>
			</div>
			<% end %>

			<% if @ujumbes.any? %>
				<%= render 'ujumbe' %>
				<% else %>
					<% unless @user == current_user %>
						<p class="lead text-center"><%= @user.name %> n'a pas encore publié de proposition</p>
					<% end %>
				<% end %>

		</div>
	


	<!-- FOLLOWED UJUMBES -->
	<div class="row">
	
				<p class="lead text-center"><b>Propositions et suggestions suivies</b></p>
		
				<%= render 'followedujumbe' %>
			</div>

		</div>

</div>

app/views/users/_shortform.html.erb
<div class="col-sm-6 col-md-6">
    <div class="thumbnail alert-info">
      <!-- <img data-src="holder.js/300x200" alt="..."> -->
      <div class="caption alert-info">

        <p class="lead"><%= link_to 'Une nouvelle solution ?', new_ujumbe_path %></p>

        <%= simple_form_for(@ujumbe) do |f| %>
        <%= f.error_notification %>
          <div class="form-group">
              <%= f.text_field :title, :placeholder => "Faites une nouvelle proposition", class: 'form-control input-lg' %>
          </div>


          <div class="form-actions">
            <%= f.submit "Publiez votre proposition", :class => "btn btn-primary btn-block" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

app/views/users/_themesusers.html.erb
<% if @user.theme_education %><span class="label label-success">éducation, jeunesse</span><% end %>
		  <% if @user.theme_economy %><span class="label label-success">économie, emploi</span><% end %>
		  <% if @user.theme_housing %><span class="label label-success">logement</span><% end %>
		  <% if @user.theme_social %><span class="label label-success"> sécurité sociale, fiscalité</span><% end %>
		  <% if @user.theme_culture %><span class="label label-success"> culture, sport</span><% end %>
		  <% if @user.theme_environnement %><span class="label label-success"> environnement</span><% end %>
		  <% if @user.theme_ressources %><span class="label label-success"> eau, énergie, agriculture</span><% end %>
		  <% if @user.theme_security %><span class="label label-success"> police, armée, justice</span><% end %>
		  <% if @user.theme_scientific %><span class="label label-success"> recherche scientifique</span><% end %>
		  <% if @user.theme_foreign %><span class="label label-success"> affaires étrangères</span><% end %>

app/views/users/_topofpage.html.erb
<div class="cover">
	<%= image_tag @user.cover.url(:cover) %>
</div>

<div class="page-header">
	<div class="row">
		<div class="col-md-10 profilename">
			<h2><%= @user.name %>
			<span class="center-text">
				<!-- social network presence -->
				<%= render 'webpresence' %>

				<% if current_user == @user %>
					<%= link_to 'Editez votre profil', edit_user_path(current_user), :class => 'btn btn-primary' %>
				<% else %>
					<% if current_user.following?(@user) %>
          	<%= link_to 'Ne plus suivre ce mandataire', unfollow_user_path(@user), :class => 'btn btn-default' if @user.is_politic %>
      				<% else %>
      					<%= link_to 'Suivre ce mandataire', follow_user_path(@user), :class => 'btn btn-success' if @user.is_politic %>
      <% end %>
				<% end %>
			</span>

			<% if @user.is_politic %>
				<br><small><b><%= @user.title %></b> <% if @user.party_short.present? %>(<%= @user.party_short %>)<% end %></small>
			<% else %>
				<br><small><b><%= @user.profession %></b></small>
						<% end %>
				<% if @user.residency.present? %>
					<small><div class="glyphicon glyphicon-map-marker pull-right"><%= @user.residency %></div></small>
		
			<% end %>
			</h2>
		</div>

		<div class="col-md-2 text-right">
			<%= image_tag @user.image.url(:thumb), :class => "img-thumbnail profilepic" %>
		</div>
	</div>
</div>

app/views/users/_ujumbe.html.erb
			<% @ujumbes.each do |ujumbe| %>
				<div class="col-sm-6 col-md-6">
			    <div class="panel">
      <!-- <img data-src="holder.js/300x200" alt="..."> -->
      <div class="panel-body card">
			        
			        
			<p class="text-right">
				<% if ujumbe.theme_education %><span class="label label-success">éducation, jeunesse</span><% end %>
      <% if ujumbe.theme_economy %><span class="label label-success">économie, emploi</span><% end %>
      <% if ujumbe.theme_housing %><span class="label label-success">logement</span><% end %>
      <% if ujumbe.theme_social %><span class="label label-success"> sécurité sociale, fiscalité</span><% end %>
      <% if ujumbe.theme_culture %><span class="label label-success"> culture, sport</span><% end %>
      <% if ujumbe.theme_environnement %><span class="label label-success"> environnement</span><% end %>
      <% if ujumbe.theme_ressources %><span class="label label-success"> eau, énergie, agriculture</span><% end %>
      <% if ujumbe.theme_security %><span class="label label-success"> police, armée, justice</span><% end %>
      <% if ujumbe.theme_scientific %><span class="label label-success"> recherche scientifique</span><% end %>
      <% if ujumbe.theme_foreign %><span class="label label-success"> affaires étrangères</span><% end %>
    	</p>

    	<div class="title"><%= link_to truncate(ujumbe.title, :length => 100), ujumbe_path(ujumbe) %></div>
    </div>

<div class="panel-footer">
	<div class="row">
		<div class="col-md-5 col-md-offset-7">
			<% if current_user.following?(ujumbe) %>
        <%= link_to unfollow_ujumbe_path(ujumbe) do %>
            <%= content_tag(:i, " " ,:class=> 'fa fa-thumbs-down btn btn-default pull-right') -%>
        <% end %>
    	<% else %>
      	<%= link_to follow_ujumbe_path(ujumbe) do %>
            <%= content_tag(:i, " " ,:class=> 'fa fa-thumbs-up btn btn-success pull-right') -%>
        <% end %>   
    	<% end %>
    	
    	<%= link_to ujumbe_path(ujumbe) do %>
        <%= content_tag(:i, " " ,:class=> 'fa fa-eye btn btn-default pull-right') -%>
      <% end %>
    </div>
  </div>
</div>

</div> <!-- end panel -->

</div> <!-- end col-md-6 -->
			 
<% end %>

			

app/views/users/_webpresence.html.erb
<%= link_to 'Facebook', @user.facebook_url, :target => "_blank", :class => 'btn btn-default' if @user.facebook_url.present? %>
<%= link_to 'Linkedin', @user.linkedin_url, :target => "_blank", :class => 'btn btn-default' if @user.linkedin_url.present? %>
<%= link_to 'Twitter', @user.twitter_url, :target => "_blank", :class => 'btn btn-default' if @user.twitter_url.present? %>
<%= link_to 'Website', @user.website_url, :target => "_blank", :class => 'btn btn-default' if @user.website_url.present? %>

app/views/users/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="page-header">
	<h1>Editez votre profil</h1>
	<p><%= link_to 'Cliquez ici pour modifier votre nom ou mot de passe', edit_user_registration_path %></p>
  <% unless current_user.is_politic %>
    <%= link_to 'Je suis candidat/mandataire politique', "mailto:contact@ujumbox.com", :class => "btn btn-success btn-block btn-lg" %>
    <small><b>Pour publier vos propositions, vous devez convertir votre profil en profil politique</b></small>
  <% end %>
</div>
  
    
    	<%= simple_form_for(@user) do |f| %>
 


    <!-- FOR DEV PURPOSE <%= f.check_box :is_politic %> politicien </li> -->

    <div class="form-group">
      <%= f.label :name, "Votre nom" %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
    </div>

  	<div class="form-group">
	    <%= f.label :image, "Votre photo de profil" %>
	    <%= f.file_field :image, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :cover, "Votre photo de couverture" %>
	    <%= f.file_field :cover, class: "form-control" %>
	  </div>

	  <div class="form-group">
      <%= f.label :residency, "Votre commune/région de résidence" %>
      <%= f.text_field :residency, class: 'form-control' %>
    </div>

    <% if current_user.is_politic %>
    	<div class="form-group">
        <%= f.label :party, "Votre parti" %>
        <%= f.text_field :party, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :party_short, "Votre parti, en abrégé" %>
        <%= f.text_field :party_short, class: 'form-control' %>
      </div>
    <% end %>

    <% if current_user.is_politic %>
      <div class="form-group">
        <%= f.label :title, "Votre titre ou votre candidature" %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :profession, "Votre activité professionnelle principale" %>
      <%= f.text_field :profession, class: 'form-control' %>
    </div>

    <% if current_user.is_politic %>
      <div class="form-group">
        <%= f.label :career, "Votre parcours politique et/ou associatif" %>
        <%= f.text_area :career, rows: "7", class: 'form-control' %>
      </div>

      	<div class="form-group">
        <%= f.label :achievements, "Vos principales réalisations" %>
        <%= f.text_area :achievements, rows: "7", class: 'form-control' %>
      </div>
    <% end %>

<div class="form-group">
  <% if current_user.is_politic %>
    <%= f.label :action_areas, "Vos principaux domaines d'action" %>
  <% else %>
    <%= f.label :action_areas, "Vos principaux centres d'intérêt politiques" %>
  <% end %>
    <ul class="list-group">
		  <li class="list-group-item"><%= f.check_box :theme_education %> éducation, jeunesse</li>
		  <li class="list-group-item"><%= f.check_box :theme_economy %> économie, emploi</li>
		  <li class="list-group-item"><%= f.check_box :theme_housing %> logement</li>
		  <li class="list-group-item"><%= f.check_box :theme_social %> sécurité sociale, fiscalité</li>
		  <li class="list-group-item"><%= f.check_box :theme_culture %> culture, sport</li>
		  <li class="list-group-item"><%= f.check_box :theme_environnement %> environnement, aménagement du territoire</li>
		  <li class="list-group-item"><%= f.check_box :theme_ressources %> eau, énergie, agriculture</li>
		  <li class="list-group-item"><%= f.check_box :theme_security %> police, armée, justice</li>
		  <li class="list-group-item"><%= f.check_box :theme_scientific %> recherche scientifique</li>
		  <li class="list-group-item"><%= f.check_box :theme_foreign %> affaires étrangères</li>
		</ul>
</div>

Vos présences web :
    <div class="form-group">
      <%= f.text_field :facebook_url, :placeholder => "http://facebook.com/...", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_field :linkedin_url, :placeholder => "http://linkedin.com/in/...", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_field :twitter_url, :placeholder => "http://twitter.com/...", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_field :website_url, :placeholder => "http://...", class: "form-control" %>
    </div>

  <div class="form-actions">
    <%= f.submit "Modifiez votre profil", :class => "btn btn-primary" %>
  </div>
<% end %>
</div>


<!-- Include Twitter Bootstrap and jQuery: -->
<link rel="stylesheet" href="css/bootstrap.min.css" type="text/css"/>
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
 
<!-- Include the plugin's CSS and JS: -->
<script type="text/javascript" src="js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="css/bootstrap-multiselect.css" type="text/css"/>
 
<!-- Initialize the plugin: -->
<script type="text/javascript">
  $(document).ready(function() {
    $('.multiselect').multiselect();
  });

</script>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render 'topofpage' %>

<!-- View if the profile is politician -->
<% if @user.is_politic %>

	<%= render 'ifpolitic' %>

<% else %>

	<%= render 'ifcitizen' %>

<% end %>