config/routes.rb
Ujumbox::Application.routes.draw do
  resources :acts
  resources :ujumbes

  root :to => "ujumbes#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
  	member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    resources :acts
  end

  get "about" => "about#show"
  get "politics" => "home#politics"
  get "citizen" => "home#citizen"
  get "rosemefalessi" => "users#show", defaults: { id: "10" }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@users = User.all
		@user = current_user
	end

	def politics
	end

	def citizen
	end
end

app/views/home/_index.html.erb
<div class="homebg">
 
    
       
      <!-- <h4 class="text-center">ujumbox permet aux citoyens et aux politiques d'ouvrir un dialogue <b>permanent</b> via des suggestions et des propositions <b>concrètes</b>, sur base de leurs <b>centres d'intérêts</b></h4> -->
    
    <div class="col-md-6 col-md-offset-6">
      <h2 class="valueprop text-right">Il y a plus simple pour <br><span class="bigger">vous souvenir</span> <br>des propositions de <br><span class="bigger">vos politiques</span></h2> 
  <!-- <div class="namefront text-center">ujumbox</div>
  <div class="baseline text-center blujumbox"><strong>votre boîte noire politique</strong></div> -->
</div>



<br><br><br>

<div class="container morefront">  
      <p class="text-center">

        <%= link_to 'En savoir plus', about_path, :class => "btn btn-default btn-lg" %></p>
</div>



  
</div>
   <div class="altbg-signup">
    <div class="container">
      <div class="form-inline text-center">
        <p><%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div class="form-group">
            <%= f.email_field :email, :autofocus => true, :placeholder => "email", class: "form-control input-lg" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, :placeholder => "mot de passe", class: "form-control input-lg" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password_confirmation, :placeholder => "confirmer mot de passe", class: "form-control input-lg" %>
          </div>

          <div class="form-group">
            <%= f.submit "s'inscrire gratuitement", class: "btn btn-info btn-lg" %>
          </div>
          <!-- <br><span class="center"><small><%= t("home.you_accept_terms") %><%= link_to t("home.our_terms"), "#" %>)</small></span> -->
        <% end %>
      </p>
      </div>
  </div>
</div>


<div class="altbg-white">
  <div class="container">
<h1 class="text-center big">Comment ça marche ?</h1>



<h3 class="text-center ujumbox big">
  <span class="bigger">ujumbox</span> citoyens
  <br><small>un aide-mémoire pour votre prochain vote</small>
</h3>
      <div class="row">
        <div class="col-md-4 text-center">
          <i class="fa fa-heart fa-5x blujumbox"></i>
          <p class="lead">Indiquez les <b>domaines qui vous tiennent à coeur</b></p>
        </div>
        <div class="col-md-4 text-center">
          <i class="fa fa-bullhorn fa-5x blujumbox"></i>
           <p class="lead">Emettez des <b>suggestions</b> selon vos préoccupations</p>
        </div>
        <div class="col-md-4 text-center">
          <i class="fa fa-tachometer fa-5x blujumbox"></i>
          <p class="lead">Consultez les <b>propositions liées</b> à vos préoccupations</p>
        </div>
      </div>
      <br>
      <div class="text-center"><%= link_to "S'inscrire", new_user_registration_path, :class => "btn btn-info btn-lg" %></div>

<br><br>

<h3 class="text-center ujumbox big">
  <span class="bigger">ujumbox</span> politiques
  <br><small>un baromètre pour établir votre prochain programme électoral</small>
</h3>
      <div class="row">
        <div class="col-md-4 text-center">
          <i class="fa fa-suitcase fa-5x blujumbox"></i>
          <p class="lead">Indiquez vos <b>domaines prioritaires d'action</b> politique</p>
        </div>
        <div class="col-md-4 text-center">
          <i class="fa fa-crosshairs fa-5x blujumbox"></i>
           <p class="lead">Publiez vos propositions concrètes, de manière <b>ciblée</b></p>
        </div>
        <div class="col-md-4 text-center">
          <i class="fa fa-thumbs-up fa-5x blujumbox"></i>
          <p class="lead">Observez le <b>soutien obtenu</b>, proposition par proposition</p>
        </div>
      </div>
      <br>
      <div class="text-center"><%= link_to "S'inscrire", new_user_registration_path, :class => "btn btn-info btn-lg" %></div>


    
    
   
    
    
    


  </div>
</div>


<div class="altbg-end">
<div class="container text-center">
  <p class="lead">Nous contacter :</p>
  <%= link_to "http://facebook.com/ujumbox", :class => 'btn btn-default btn-lg', :target => "_blank" do %>  
    <i class="fa fa-facebook fw"> Facebook</i>
  <% end %>
  <%= link_to "mailto:contact@ujumbox.com", :class => 'btn btn-default btn-lg', :target => "_blank" do %>  
    <i class="fa fa-envelope fw"> Email</i>
  <% end %>
  <!-- <%= link_to "mailto:contact@ujumbox.com", :class => 'btn btn-default btn-lg', :target => "_blank" do %>  
    <i class="fa fa-bullhorn"> Publier vos propositions</i>
  <% end %> -->

  </div>
  </div>
</div>






	

app/views/home/citizen.html.erb
citizen.html.erb

app/views/home/politics.html.erb
		<h1 class="text-center">Constituez et fidélisez votre base électorale <br> proposition après proposition</h1> 



<div class="namefront text-center">ujumbox</div>
  <div class="baseline text-center blujumbox"><strong>politics</strong></div>

Itinéraire de campagne

Publication d'une proposition ujumbox

Réception par tout citoyen inscrit, intéressé sur le sujet (même s'il ne vous connaît pas !)

Plébiscite par les citoyens qui sont séduits par votre proposition

Ajout d'un premier, puis d'un second, voire un troisième act en vue de porter la proposition

Chaque acte, envoyé à tout citoyen intéressé, donne du crédit à votre proposition, puis à votre action politique en général (votre engagement)

Et pour cause, les citoyens inscrits ne se contentent plus de plébisciter vos propositions et actes, mais votre profil politique en soi

Et bingo ! Vous convaincez, par le fond de votre action politique quotidienne

<!-- Communication sur le fond
dans une forme aussi facile qu'un tweet
- faites une proposition, concrète, facilement digérable par le citoyen

Anatomie d'une proposition ujumbox

Portabilité de vos propositions
- partager votre proposition

Outil de ciblage de votre électoral potentiel
- cibler automatiquement les destinataires pertinents de votre proposition

Outil de constitution de votre base électorale
- constituer ainsi votre base électorale
- soyez à l'écoute des suggestions
- observez les propositions qui receuillent la majorité des suffrages au quotidien

- fidélisez votre base électorale ainsi constituée

Grâce à ujumbox, votre visibilité et votre impact ne dépend plus des médias mais de votre action politique au quotidien -->