config/routes.rb
Ujumbox::Application.routes.draw do
  resources :acts
  resources :ujumbes

  root :to => "ujumbes#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
  	member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :ujumbes do
    resources :acts
  end

  get "about" => "about#show"
  get "politics" => "home#politics"
  get "citizen" => "home#citizen"
  get "rosemefalessi" => "users#show", defaults: { id: "10" }

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <p><div class="container text-center footing">
  	<div class="fb-like" data-href="http://www.ujumbox.com" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div></p>
  	<p>réalisé par upcetera SPRL | copyright 2014</p>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <p><div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div></p>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ujumbox', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
	
  
  <li><%= link_to 'Accueil', ujumbes_path %></li>
  <% unless current_user.is_politic %><li><%= link_to 'Vous êtes candidat/mandataire ?', "mailto:contact@ujumbox.com" %></li><% end %>
  <li><%= link_to 'A propos', about_path %></li>
  <!-- <li><%= link_to 'Blog', "http://ujumbox.tumblr.com" %></li> -->

  <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name if @user.present? %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Consultez votre profil', user_path(current_user) %></li>
            <li><%= link_to 'Editez votre profil', edit_user_path(current_user) %></li>
            <li role="presentation" class="divider"></li>
            <% unless current_user.is_politic %><li><%= link_to 'Devenir utilisateur politique', "mailto:contact@ujumbox.com" %></li><% end %>
            <li><%= link_to 'Votre compte', edit_user_registration_path %></li>
            <li role="presentation" class="divider"></li>
              <li><%= link_to 'Déconnexion', destroy_user_session_path, :method=>'delete' %></li>
          </ul>
  </li>

<% else %>
   <!-- <li><%= link_to 'Politiques', politics_path %></li>
   <li><%= link_to 'Citoyens', citizen_path %></li> -->
    <li><%= link_to 'A propos', about_path %></li>
   <!-- <li><%= link_to 'Blog', "http://ujumbox.tumblr.com", :target => "_blank" %></li> -->
  <li><%= link_to 'Connexion', new_user_session_path %></li>
  <li><%= link_to 'Inscription', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
  <head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ujumbox - boîte à messages politique" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Parce que la démocratie ne se limite pas aux périodes électorales, ujumbox permet aux citoyens et aux politiques d'ouvrir un dialogue permanent via des suggestions et des propositions concrètes, sur base de leurs centres d'intérêts" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- for Google -->
<meta name="description" content="Parce que la démocratie ne se limite pas aux périodes électorales, ujumbox permet aux citoyens et aux politiques d'ouvrir un dialogue permanent via des suggestions et des propositions concrètes, sur base de leurs centres d'intérêts" />
<meta name="keywords" content="digital democracy, démocracie participative, politics, content marketing, elections" />

<meta name="author" content="UPcetera" />
<meta name="copyright" content="" />
<meta name="application-name" content="ujumbox - boîte à messages politique" />

<!-- for Facebook -->          
<meta property="og:title" content="ujumbox - boîte à messages politique" />
<meta property="og:type" content="web application" />
<meta property="og:image" content="logo_ujumbox.png" />
<meta property="og:url" content="http://ujumbox.com" />
<meta property="og:description" content="ujumbox permet aux citoyens et aux politiques d'ouvrir un dialogue permanent via des suggestions et des propositions concrètes, sur base de leurs centres d'intérêts" />

<!-- for Twitter -->          
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="" />
<meta name="twitter:description" content="" />
<meta name="twitter:image" content="" />



  </head>
  <body>
    <header>

      <%= render 'layouts/navigation' %>
    </header>
 
        <% if user_signed_in? %>
       <div class="container">
         <%= render 'layouts/messages' %>
       </div>
          <div class="container">
            <%= yield %>
          </div>
        
        <% else %>
           <div class="container">
          <%= render 'layouts/messages' %>
        </div>
          <%= yield %>

          <!-- <footer>
            <%= render 'layouts/footer' %>
          </footer> -->
            
        <% end %>
 
    

<!-- facebook like -->
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&appId=352345548176853&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  </body>
</html>